name: Cloud Function Deployment

on:
  push:
    branches: ["dev", "master"]

permissions:
  contents: 'read'
 # pages: write
  id-token: 'write'

jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Repo
      uses: 'actions/checkout@v4'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Installing dependencies
      run: |
        npm install
        npm install -g firebase-tools
        cd functions && npm install

    - name: Firebase authentication
      #run: |
       # firebase use ${{ secrets.PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: '${{ secrets.PROJECT_ID }}'
        workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
        #service_account: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARTA_C98E1 }}'

    - name: Deploy functions
      run: firebase deploy --only functions --project ${{ secrets.PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'