name: Build and Test
run-name: ${{ github.actor }} launched the Build-and-Test workflow 🚀
on:
  pull_request:
    branches: ["dev", "master"]
  push:
    paths:
      - 'functions/**'
      - '.github/**'


permissions:
  contents: 'read'
  # id-token: 'write'

jobs:
  build_and_test:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Repo
      uses: 'actions/checkout@v4'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Installing dependencies
      run: |
        npm install
        npm install -g firebase-tools
        cd functions && npm install

    - name: Run Lint Codebase
      run: cd functions && npm run lint

    - name: Run Unit Tests
      run: cd functions && npm run test